#!/usr/bin/env python3
"""Hash-pin contract for the release workflow (code-scanning alerts #14/#15).

The job that builds the distribution PyPI receives used to run
``pip install build twine check-wheel-contents`` and
``python -m pip install --upgrade pip``: version-free, hash-free installs, so the
toolchain that produced and inspected the published artifact was whatever PyPI
served at that minute. OpenSSF Scorecard's Pinned-Dependencies check flags
exactly that. This gate keeps the release path at the stronger state:

1. In every release workflow each ``pip install`` is either

   * hash-locked -- ``--require-hashes`` plus ``-r <lock>``, nothing else
     positional; or
   * a local wheel -- ``--no-deps`` and only ``*.whl`` paths, which installs
     the artifact the job itself just built and verified.

   Anything else, including ``--upgrade pip`` and ``uv pip install``, fails.
2. Every lock such an install names is a real hash lock: each entry is an exact
   ``name==version`` pin carrying at least one well-formed digest, and there
   are no nested ``-r``/``-c``/``-e`` lines that would pull in unhashed input.
3. The lock covers every top-level requirement of its ``.in`` source, and it
   was compiled for the interpreter the workflow runs (``python-version``),
   because environment markers are resolved for exactly one interpreter.
4. The locked build backend satisfies ``[build-system] requires`` in
   ``pyproject.toml`` -- the workflow builds with ``--no-isolation``, so the
   locked setuptools IS the backend, and a lock that drifted below the
   project's floor would build with an unsupported one.
5. Its header regeneration command still generates hashes and does not carry
   the spurious ``--no-index`` that pip-tools 7.6.1 writes under click >= 8.3
   (see ``.github/requirements/release.in``).
6. The release workflow is parseable YAML as far as inline values go (see
   :func:`plain_scalar_defects`): it runs only on release, so nothing else
   would notice before then.

Standard library only, like the rest of the quality contract.
"""

from __future__ import annotations

import re
import shlex
import sys
from dataclasses import dataclass, field
from pathlib import Path

try:  # pragma: no cover - exercised only on Python < 3.11
    import tomllib
except ModuleNotFoundError:  # pragma: no cover
    tomllib = None  # type: ignore[assignment]

ROOT = Path(__file__).resolve().parents[2]

#: Workflows that build or publish the distribution. Listed rather than inferred,
#: so that renaming one cannot silently drop it from the gate (it must exist).
RELEASE_WORKFLOWS: tuple[str, ...] = ("pypi.yml",)
#: A workflow containing one of these publishes to PyPI and must be listed above.
PUBLISH_MARKERS: tuple[str, ...] = ("pypa/gh-action-pypi-publish", "twine upload")

#: ``pip install`` options that consume the following token as their value, so
#: it is not mistaken for a package argument. An option missing from this set
#: makes its value look positional, which fails the contract -- the safe side.
_VALUE_OPTIONS = frozenset(
    {
        "-r",
        "--requirement",
        "-c",
        "--constraint",
        "-e",
        "--editable",
        "-t",
        "--target",
        "--platform",
        "--python-version",
        "--implementation",
        "--abi",
        "--root",
        "--prefix",
        "--src",
        "--upgrade-strategy",
        "--only-binary",
        "--no-binary",
        "--progress-bar",
        "--root-user-action",
        "--report",
        "-i",
        "--index-url",
        "--extra-index-url",
        "-f",
        "--find-links",
        "-C",
        "--config-settings",
        "--global-option",
        "--trusted-host",
        "--log",
        "--cache-dir",
        "--proxy",
        "--retries",
        "--timeout",
        "--exists-action",
        "--cert",
        "--client-cert",
        "--keyring-provider",
        "--python",
        "--group",
    }
)
_REQUIREMENT_OPTIONS = frozenset({"-r", "--requirement"})
_EDITABLE_OPTIONS = frozenset({"-e", "--editable"})
_SHELL_OPERATORS = frozenset({"&&", "||", ";", "|", "&", ";;", "(", ")"})
_DIGEST_LENGTHS = {"sha256": 64, "sha384": 96, "sha512": 128}

_RUN_PREFIX_RE = re.compile(r"^\s*(?:-\s+)?run:\s*(.*)$")
_PYTHON_RE = re.compile(r"^(?:.*/)?python(?:\d+(?:\.\d+)?)?$")
_PIP_RE = re.compile(r"^(?:.*/)?pip(?:\d+(?:\.\d+)?)?$")
_ENV_ASSIGNMENT_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*=")
_PYTHON_VERSION_RE = re.compile(r"^\s*python-version:\s*['\"]?([^'\"\s#]+)")
_HEADER_PYTHON_RE = re.compile(
    r"^#\s*This file is autogenerated by pip-compile with Python (\d+\.\d+)\s*$"
)
_HEADER_COMMAND_RE = re.compile(r"^#\s+(pip-compile\s.*)$")
_NAME_RE = re.compile(r"^([A-Za-z0-9](?:[A-Za-z0-9._-]*[A-Za-z0-9])?)")
_RELEASE_RE = re.compile(r"^\d+(?:\.\d+)*$")
_SPEC_RE = re.compile(r"^\s*(~=|==|!=|<=|>=|<|>)\s*([^\s,]+)\s*$")


def normalise_name(name: str) -> str:
    """PEP 503 normalisation, so ``Check_Wheel.Contents`` names one project."""
    return re.sub(r"[-_.]+", "-", name).lower()


@dataclass(frozen=True)
class PipInstall:
    """One ``pip install`` invocation found in a workflow's shell text."""

    line: int
    requirement_files: tuple[str, ...]
    positionals: tuple[str, ...]
    flags: frozenset[str]


@dataclass
class Lock:
    """What a parsed hash lock pins, and what it was compiled for."""

    pins: dict[str, str] = field(default_factory=dict)
    python: str | None = None
    command: str | None = None


def _logical_lines(text: str) -> list[tuple[int, str]]:
    """Join backslash continuations, keeping the first physical line number."""
    out: list[tuple[int, str]] = []
    pending: list[str] = []
    start = 0
    for number, raw in enumerate(text.splitlines(), start=1):
        if not pending:
            start = number
        stripped = raw.rstrip()
        if stripped.endswith("\\"):
            pending.append(stripped[:-1])
            continue
        pending.append(stripped)
        out.append((start, " ".join(pending)))
        pending = []
    if pending:
        out.append((start, " ".join(pending)))
    return out


def _shell_text(line: str) -> str | None:
    """The part of a workflow line that the runner hands to the shell.

    A ``run:`` key contributes its inline value; a block-scalar indicator
    (``|``, ``>-`` ...) contributes nothing on its own line. Every other line
    is scanned as a possible block-scalar body line -- over-inclusive on
    purpose: a false match can only produce an error, never hide an install.
    YAML comment lines need no case of their own: the tokeniser applies shell
    comment rules, under which ``# pip install x`` is empty in both languages
    (a mutation probe that removed an explicit skip here changed no outcome).
    """
    match = _RUN_PREFIX_RE.match(line)
    if match:
        value = match.group(1).strip()
        if not value or value[0] in "|>":
            return None
        return value
    return line


def _segments(tokens: list[str]) -> list[list[str]]:
    segments: list[list[str]] = [[]]
    for token in tokens:
        if token in _SHELL_OPERATORS:
            segments.append([])
        else:
            segments[-1].append(token)
    return [segment for segment in segments if segment]


def _install_arguments(segment: list[str]) -> list[str] | None:
    """Arguments after ``install`` for a recognised pip command, else ``None``.

    Recognised: ``pip``/``pip3[.N]`` and
    ``python[3[.N]] [interpreter options] -m pip``, after optional leading
    ``VAR=value`` assignments, then pip's own global options, then
    ``install``. Global options are skipped rather than required absent:
    ``pip --disable-pip-version-check install x`` is an install too, and a
    parser that only looked for ``pip install`` side by side would let it
    through unchecked.
    """
    words = list(segment)
    while words and _ENV_ASSIGNMENT_RE.match(words[0]):
        words.pop(0)
    start: int | None = None
    if words and _PIP_RE.match(words[0]):
        start = 1
    elif words and _PYTHON_RE.match(words[0]):
        for index in range(1, len(words) - 1):
            if words[index] == "-m":
                if words[index + 1] == "pip":
                    start = index + 2
                break
    if start is None:
        return None
    index = start
    while index < len(words) and words[index].startswith("-"):
        name, has_inline, _value = words[index].partition("=")
        index += 1
        if name in _VALUE_OPTIONS and not has_inline:
            index += 1
    if index < len(words) and words[index] == "install":
        return words[index + 1 :]
    return None


def _mentions_pip_install(segment: list[str]) -> bool:
    """A ``pip`` word (any spelling) with ``install`` anywhere after it.

    The net for everything :func:`_install_arguments` does not recognise --
    ``uv pip install``, ``sudo pip install``, ``"$PY" -m pip install`` -- so
    that an unfamiliar spelling is reported instead of silently skipped.
    """
    for index, word in enumerate(segment):
        if _PIP_RE.match(word) and "install" in segment[index + 1 :]:
            return True
    return False


def find_pip_installs(text: str) -> tuple[list[PipInstall], list[str]]:
    """Every ``pip install`` in a workflow, plus the ones it cannot read.

    The second list holds ``"<line>: <reason>"`` entries for text that
    mentions a pip install the parser does not understand. Those fail the
    contract rather than being skipped: an unreadable install is an unverified
    install.
    """
    installs: list[PipInstall] = []
    unreadable: list[str] = []
    for number, line in _logical_lines(text):
        shell = _shell_text(line)
        if shell is None or "pip" not in shell or "install" not in shell:
            continue
        lexer = shlex.shlex(shell, posix=True, punctuation_chars=True)
        lexer.whitespace_split = True
        try:
            tokens = list(lexer)
        except ValueError as exc:
            unreadable.append(f"{number}: cannot tokenise shell text ({exc})")
            continue
        for segment in _segments(tokens):
            arguments = _install_arguments(segment)
            if arguments is None:
                if _mentions_pip_install(segment):
                    unreadable.append(
                        f"{number}: unrecognised pip invocation {' '.join(segment)!r}"
                    )
                continue
            installs.append(_parse_install(number, arguments))
    return installs, unreadable


def _parse_install(number: int, arguments: list[str]) -> PipInstall:
    requirement_files: list[str] = []
    positionals: list[str] = []
    flags: set[str] = set()
    index = 0
    while index < len(arguments):
        word = arguments[index]
        index += 1
        if word.startswith("-") and word != "-":
            name, has_inline, value = word.partition("=")
            flags.add(name)
            if name in _VALUE_OPTIONS and not has_inline and index < len(arguments):
                value = arguments[index]
                index += 1
            if name in _REQUIREMENT_OPTIONS and value:
                requirement_files.append(value)
            continue
        positionals.append(word)
    return PipInstall(
        line=number,
        requirement_files=tuple(requirement_files),
        positionals=tuple(positionals),
        flags=frozenset(flags),
    )


def classify(install: PipInstall) -> str | None:
    """``None`` when the install satisfies the contract, else the reason."""
    if install.flags & _EDITABLE_OPTIONS:
        return "editable install in a release workflow"
    if "--require-hashes" in install.flags:
        if install.positionals:
            return (
                f"--require-hashes install also names unhashed packages {list(install.positionals)}"
            )
        if not install.requirement_files:
            return "--require-hashes without a -r lock file"
        return None
    if (
        install.positionals
        and not install.requirement_files
        and "--no-deps" in install.flags
        and all(item.endswith(".whl") and "://" not in item for item in install.positionals)
    ):
        return None
    return (
        "not hash-pinned: use --require-hashes -r <lock>, or --no-deps with local *.whl paths only"
    )


def parse_lock(text: str) -> tuple[Lock, list[str]]:
    """Parse a pip-compile hash lock; the second value lists its defects."""
    lock = Lock()
    errors: list[str] = []
    for raw in text.splitlines():
        header = _HEADER_PYTHON_RE.match(raw)
        if header:
            lock.python = header.group(1)
        command = _HEADER_COMMAND_RE.match(raw)
        if command:
            lock.command = command.group(1).strip()
    for number, line in _logical_lines(text):
        content = line.split(" #", 1)[0].strip()
        if not content or content.startswith("#"):
            continue
        if content.startswith("-"):
            errors.append(
                f"line {number}: option line {content.split()[0]!r} -- a lock "
                "must not pull in other files or indexes"
            )
            continue
        spec, _sep, rest = content.partition(" --hash=")
        hashes = re.findall(r"--hash=(\w+):(\S+)", "--hash=" + rest) if _sep else []
        leftover = re.sub(r"--hash=\S+", "", "--hash=" + rest).strip() if _sep else ""
        name_match = _NAME_RE.match(spec)
        if name_match is None:
            errors.append(f"line {number}: unreadable requirement {spec!r}")
            continue
        requirement = spec.split(";", 1)[0].strip()
        pinned = re.fullmatch(
            r"([A-Za-z0-9][A-Za-z0-9._-]*)(?:\[[^\]]*\])?==([^=*\s]+)", requirement
        )
        if pinned is None:
            errors.append(f"line {number}: {requirement!r} is not an exact == pin")
            continue
        if not hashes:
            errors.append(f"line {number}: {requirement!r} carries no --hash")
            continue
        if leftover:
            errors.append(f"line {number}: unexpected text after the hashes {leftover!r}")
            continue
        bad = [
            f"{algorithm}:{digest}"
            for algorithm, digest in hashes
            if _DIGEST_LENGTHS.get(algorithm) != len(digest)
            or not re.fullmatch(r"[0-9a-f]+", digest)
        ]
        if bad:
            errors.append(f"line {number}: malformed digest(s) {bad}")
            continue
        lock.pins[normalise_name(pinned.group(1))] = pinned.group(2)
    if not lock.pins:
        errors.append("the lock pins nothing")
    return lock, errors


def requirement_names(text: str) -> list[str]:
    """Top-level project names of a ``.in`` requirements file."""
    names = []
    for line in text.splitlines():
        content = line.split("#", 1)[0].strip()
        if not content:
            continue
        match = _NAME_RE.match(content)
        if match:
            names.append(normalise_name(match.group(1)))
    return names


def _release_tuple(version: str) -> tuple[int, ...] | None:
    return tuple(int(part) for part in version.split(".")) if _RELEASE_RE.match(version) else None


def _compare(left: tuple[int, ...], right: tuple[int, ...]) -> int:
    width = max(len(left), len(right))
    a = left + (0,) * (width - len(left))
    b = right + (0,) * (width - len(right))
    return (a > b) - (a < b)


def satisfies(version: str, specifier: str) -> bool | None:
    """Whether ``version`` meets a comma-separated specifier.

    Only final releases (``N(.N)*``) and the operators ``~= == != <= >= < >``
    are evaluated; anything else returns ``None`` so the caller fails closed
    instead of guessing at pre-release or wildcard semantics.
    """
    have = _release_tuple(version)
    if have is None:
        return None
    for clause in filter(None, (part.strip() for part in specifier.split(","))):
        match = _SPEC_RE.match(clause)
        if match is None:
            return None
        operator, target = match.groups()
        want = _release_tuple(target)
        if want is None:
            return None
        order = _compare(have, want)
        if operator == "~=":
            if len(want) < 2:
                return None
            ok = order >= 0 and have[: len(want) - 1] == want[:-1]
        else:
            ok = {
                "==": order == 0,
                "!=": order != 0,
                "<=": order <= 0,
                ">=": order >= 0,
                "<": order < 0,
                ">": order > 0,
            }[operator]
        if not ok:
            return False
    return True


def build_system_requires(pyproject_text: str) -> list[str] | None:
    """``[build-system] requires``, or ``None`` when it cannot be read."""
    if tomllib is None:  # pragma: no cover
        return None
    try:
        data = tomllib.loads(pyproject_text)
    except tomllib.TOMLDecodeError:
        return None
    requires = data.get("build-system", {}).get("requires")
    if not isinstance(requires, list) or not all(isinstance(r, str) for r in requires):
        return None
    return list(requires)


def check_lock(lock_path: Path, root: Path) -> tuple[Lock | None, list[str]]:
    """Validate one lock file and its relation to its ``.in`` and pyproject."""
    shown = lock_path.relative_to(root) if lock_path.is_relative_to(root) else lock_path
    if not lock_path.is_file():
        return None, [f"{shown}: lock file does not exist"]
    lock, defects = parse_lock(lock_path.read_text(encoding="utf-8"))
    errors = [f"{shown}: {defect}" for defect in defects]
    if lock.python is None:
        errors.append(f"{shown}: no 'autogenerated by pip-compile with Python X.Y' header")
    if lock.command is None:
        errors.append(f"{shown}: no pip-compile command in the header")
    else:
        options = lock.command.split()
        if "--generate-hashes" not in options:
            errors.append(f"{shown}: header command does not --generate-hashes")
        if "--no-index" in options:
            errors.append(
                f"{shown}: header command carries --no-index (pip-tools/click "
                "header bug); regenerate with click<8.3, see release.in"
            )
    source = lock_path.with_suffix(".in")
    if not source.is_file():
        errors.append(f"{shown}: missing requirements source {source.name}")
    else:
        missing = [
            n for n in requirement_names(source.read_text(encoding="utf-8")) if n not in lock.pins
        ]
        if missing:
            errors.append(f"{shown}: does not lock {missing} from {source.name}; recompile")
    requires = build_system_requires((root / "pyproject.toml").read_text(encoding="utf-8"))
    if requires is None:
        why = " (tomllib needs Python 3.11+)" if tomllib is None else ""
        errors.append(f"pyproject.toml: cannot read [build-system] requires{why}")
    else:
        for requirement in requires:
            name_match = _NAME_RE.match(requirement)
            if name_match is None:
                errors.append(f"pyproject.toml: unreadable build requirement {requirement!r}")
                continue
            name = normalise_name(name_match.group(1))
            specifier = requirement[name_match.end() :].split(";", 1)[0].strip()
            locked = lock.pins.get(name)
            if locked is None:
                errors.append(
                    f"{shown}: build backend requirement {requirement!r} is not "
                    "locked, but the release builds with --no-isolation"
                )
                continue
            verdict = satisfies(locked, specifier)
            if verdict is None:
                errors.append(
                    f"{shown}: cannot evaluate locked {name}=={locked} against {specifier!r}"
                )
            elif not verdict:
                errors.append(
                    f"{shown}: locked {name}=={locked} violates pyproject.toml "
                    f"build-system requirement {requirement!r}"
                )
    return lock, errors


_KEY_VALUE_RE = re.compile(r"^(\s*(?:-\s+)?)([A-Za-z0-9_.-]+):(?:\s+(.*))?$")


def plain_scalar_defects(text: str) -> list[str]:
    """Inline plain-scalar values that YAML cannot parse.

    Inside an unquoted (plain) scalar, ``": "`` and a trailing ``":"`` are
    mapping indicators, so ``run: pip install --only-binary :all: -r x`` makes
    the WHOLE file unparsable. A release workflow only runs when a release is
    published, so that error would first surface on release day -- and the
    zizmor gate does not catch it: measured with zizmor 1.30.1, an unparsable
    workflow is skipped with a warning and the run still exits 0 with "No
    findings". This is a narrow stdlib stand-in for a YAML parser, which the
    quality contract deliberately does not install: it reads only inline
    ``key: value`` lines and skips block-scalar bodies, which may contain
    anything.
    """
    defects: list[str] = []
    block_parent: int | None = None
    for number, line in enumerate(text.splitlines(), start=1):
        indent = len(line) - len(line.lstrip())
        if block_parent is not None:
            if not line.strip() or indent > block_parent:
                continue
            block_parent = None
        match = _KEY_VALUE_RE.match(line)
        if match is None or line.lstrip().startswith("#"):
            continue
        key_column = len(match.group(1))
        value = (match.group(3) or "").split(" #", 1)[0].rstrip()
        if not value:
            continue
        if value[0] in "|>":
            block_parent = key_column
            continue
        if value[0] in "'\"[{&*!":
            continue
        if ": " in value or value.endswith(":"):
            defects.append(
                f"{number}: inline plain scalar {value!r} contains a YAML mapping "
                "indicator (': ' or trailing ':'); use a block scalar (|) or quotes"
            )
    return defects


def check_workflow(path: Path, root: Path) -> list[str]:
    """All contract violations of one release workflow."""
    text = path.read_text(encoding="utf-8")
    shown = path.relative_to(root) if path.is_relative_to(root) else path
    installs, unreadable = find_pip_installs(text)
    errors = [f"{shown}:{entry}" for entry in unreadable]
    errors.extend(f"{shown}:{entry}" for entry in plain_scalar_defects(text))
    locked_installs = 0
    python_versions = {
        match.group(1) for line in text.splitlines() if (match := _PYTHON_VERSION_RE.match(line))
    }
    for install in installs:
        reason = classify(install)
        if reason is not None:
            errors.append(f"{shown}:{install.line}: {reason}")
            continue
        for requirement_file in install.requirement_files:
            locked_installs += 1
            lock, lock_errors = check_lock(root / requirement_file, root)
            errors.extend(lock_errors)
            if lock is None or lock.python is None:
                continue
            if not python_versions:
                errors.append(
                    f"{shown}: installs {requirement_file} but pins no python-version; "
                    "the lock only holds for the interpreter it was compiled with"
                )
            mismatched = sorted(v for v in python_versions if v != lock.python)
            if mismatched:
                errors.append(
                    f"{shown}: python-version {mismatched} differs from the Python "
                    f"{lock.python} that {requirement_file} was compiled for"
                )
    if locked_installs == 0:
        errors.append(f"{shown}: release workflow has no hash-locked tool install")
    return errors


def check(root: Path = ROOT) -> list[str]:
    """Every violation of the release hash-pin contract under ``root``."""
    workflows = root / ".github" / "workflows"
    errors: list[str] = []
    for name in RELEASE_WORKFLOWS:
        path = workflows / name
        if not path.is_file():
            errors.append(f".github/workflows/{name}: listed release workflow is missing")
            continue
        errors.extend(check_workflow(path, root))
    if workflows.is_dir():
        for path in sorted(workflows.iterdir()):
            if path.suffix not in {".yml", ".yaml"} or path.name in RELEASE_WORKFLOWS:
                continue
            text = path.read_text(encoding="utf-8")
            uncommented = "\n".join(line.split("#", 1)[0] for line in text.splitlines())
            if any(marker in uncommented for marker in PUBLISH_MARKERS):
                errors.append(
                    f".github/workflows/{path.name}: publishes to PyPI but is not in "
                    "RELEASE_WORKFLOWS, so its installs are not hash-checked"
                )
    return errors


def main() -> int:
    errors = check()
    if errors:
        print("Release hash-pin check failed:", file=sys.stderr)
        for error in errors:
            print(f"- {error}", file=sys.stderr)
        return 1
    print(f"Release hash-pin check passed for {', '.join(RELEASE_WORKFLOWS)}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
