#!/usr/bin/env python3
"""Adversarial tests for the release hash-pin contract (check_release_pins.py).

Every negative case mutates ONE aspect of a tree the positive control proves
clean, so each assertion shows the gate discriminates on that aspect alone.
"""

from __future__ import annotations

import tempfile
import unittest
from pathlib import Path

import check_release_pins as contract

HASH_A = "a" * 64
HASH_B = "b" * 64
HASH_C = "c" * 64

LOCK = f"""#
# This file is autogenerated by pip-compile with Python 3.12
# by the following command:
#
#    pip-compile --allow-unsafe --generate-hashes --strip-extras release.in
#
build==1.6.1 \\
    --hash=sha256:{HASH_A} \\
    --hash=sha256:{HASH_B}
    # via -r release.in
tomli==2.2.1 ; python_version < "3.11" \\
    --hash=sha256:{HASH_C}
    # via build

# The following packages are considered to be unsafe in a requirements file:
setuptools==84.0.0 \\
    --hash=sha256:{HASH_C}
    # via -r release.in
"""

SOURCE = "# comment\nbuild\nsetuptools>=77.0  # backend\n"

PYPROJECT = (
    '[build-system]\nrequires = ["setuptools>=77.0"]\nbuild-backend = "setuptools.build_meta"\n'
)

INSTALL = (
    "python -m pip install --require-hashes --only-binary :all: -r .github/requirements/release.txt"
)

WORKFLOW = f"""name: Publish
on: workflow_dispatch
permissions: {{}}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@0000000000000000000000000000000000000000
        with:
          python-version: "3.12"
      # pip install build   <- a comment is not an install
      - name: Install tools
        run: |
          {INSTALL}
      - run: |
          python -m build --no-isolation
          python -m pip install --force-reinstall --no-deps dist/*.whl
"""


class ReleasePinContractTests(unittest.TestCase):
    def tree(
        self,
        *,
        workflow: str = WORKFLOW,
        lock: str | None = LOCK,
        source: str | None = SOURCE,
        pyproject: str = PYPROJECT,
        extra_workflows: dict[str, str] | None = None,
    ) -> Path:
        tmp = tempfile.TemporaryDirectory()
        self.addCleanup(tmp.cleanup)
        root = Path(tmp.name)
        (root / ".github" / "workflows").mkdir(parents=True)
        (root / ".github" / "requirements").mkdir(parents=True)
        (root / ".github" / "workflows" / "pypi.yml").write_text(workflow, encoding="utf-8")
        for name, text in (extra_workflows or {}).items():
            (root / ".github" / "workflows" / name).write_text(text, encoding="utf-8")
        if lock is not None:
            (root / ".github" / "requirements" / "release.txt").write_text(lock, encoding="utf-8")
        if source is not None:
            (root / ".github" / "requirements" / "release.in").write_text(source, encoding="utf-8")
        (root / "pyproject.toml").write_text(pyproject, encoding="utf-8")
        return root

    def assert_rejected(self, errors: list[str], fragment: str) -> None:
        self.assertTrue(
            any(fragment in error for error in errors),
            f"expected an error containing {fragment!r}, got {errors}",
        )

    # --- positive controls -------------------------------------------------

    def test_positive_control_fixture_is_clean(self) -> None:
        self.assertEqual(contract.check(self.tree()), [])

    def test_repository_itself_is_clean(self) -> None:
        self.assertEqual(contract.check(contract.ROOT), [])

    # --- install recognition -----------------------------------------------

    def test_previous_release_installs_are_rejected(self) -> None:
        """The two lines code scanning flagged (#14/#15), verbatim from main."""
        workflow = WORKFLOW.replace(
            f"run: |\n          {INSTALL}",
            "run: |\n          python -m pip install --upgrade pip\n"
            "          pip install build twine check-wheel-contents",
        )
        errors = contract.check(self.tree(workflow=workflow))
        self.assertEqual(sum("not hash-pinned" in e for e in errors), 2, errors)
        self.assert_rejected(errors, "no hash-locked tool install")

    def test_global_options_between_pip_and_install_do_not_hide_it(self) -> None:
        for command in (
            "pip --disable-pip-version-check install build",
            "python -m pip --log pip.log install build",
            "python3.12 -I -m pip install build",
            "PIP_NO_CACHE_DIR=1 pip3 install build",
            "/usr/bin/pip install build",
        ):
            with self.subTest(command=command):
                workflow = WORKFLOW.replace("python -m build --no-isolation", command)
                self.assert_rejected(
                    contract.check(self.tree(workflow=workflow)), "not hash-pinned"
                )

    def test_unrecognised_pip_spellings_fail_closed(self) -> None:
        for command in (
            "uv pip install build",
            "sudo pip install build",
            '"$PYTHON" -m pip install build',
        ):
            with self.subTest(command=command):
                workflow = WORKFLOW.replace("python -m build --no-isolation", command)
                self.assert_rejected(
                    contract.check(self.tree(workflow=workflow)),
                    "unrecognised pip invocation",
                )

    def test_continuation_lines_are_joined(self) -> None:
        workflow = WORKFLOW.replace(
            "python -m build --no-isolation", "pip install \\\n            build"
        )
        self.assert_rejected(contract.check(self.tree(workflow=workflow)), "not hash-pinned")

    def test_every_segment_of_a_compound_command_is_checked(self) -> None:
        workflow = WORKFLOW.replace(INSTALL, f"{INSTALL} && pip install twine")
        self.assert_rejected(contract.check(self.tree(workflow=workflow)), "not hash-pinned")

    def test_non_install_pip_commands_are_not_installs(self) -> None:
        workflow = WORKFLOW.replace(
            "python -m build --no-isolation",
            "python -m pip check && pip --version && python -m build",
        )
        self.assertEqual(contract.check(self.tree(workflow=workflow)), [])

    # --- classification ----------------------------------------------------

    def test_hash_mode_must_not_add_unhashed_packages(self) -> None:
        workflow = WORKFLOW.replace(INSTALL, INSTALL + " twine")
        self.assert_rejected(contract.check(self.tree(workflow=workflow)), "unhashed packages")

    def test_require_hashes_needs_a_lock(self) -> None:
        workflow = WORKFLOW.replace(INSTALL, "python -m pip install --require-hashes")
        self.assert_rejected(contract.check(self.tree(workflow=workflow)), "without a -r lock")

    def test_local_wheel_rules(self) -> None:
        cases = {
            "python -m pip install dist/*.whl": "not hash-pinned",
            "python -m pip install --no-deps https://x.invalid/a.whl": "not hash-pinned",
            "python -m pip install --no-deps dist/a.tar.gz": "not hash-pinned",
            "python -m pip install --no-deps -e .": "editable install",
        }
        for command, fragment in cases.items():
            with self.subTest(command=command):
                workflow = WORKFLOW.replace(
                    "python -m pip install --force-reinstall --no-deps dist/*.whl", command
                )
                self.assert_rejected(contract.check(self.tree(workflow=workflow)), fragment)

    # --- lock integrity ----------------------------------------------------

    def test_lock_defects_are_each_rejected(self) -> None:
        cases = {
            "unhashed": (
                f"build==1.6.1 \\\n    --hash=sha256:{HASH_A} \\\n    --hash=sha256:{HASH_B}",
                "build==1.6.1",
                "carries no --hash",
            ),
            "range pin": ("build==1.6.1 \\", "build>=1.6 \\", "not an exact == pin"),
            "wildcard pin": ("build==1.6.1 \\", "build==1.* \\", "not an exact == pin"),
            "short digest": (HASH_A, "a" * 63, "malformed digest"),
            "unknown algorithm": (f"sha256:{HASH_A}", f"md5:{'a' * 32}", "malformed digest"),
            "nested file": (
                "# via -r release.in\ntomli",
                "-r other.txt\ntomli",
                "option line '-r'",
            ),
        }
        for label, (old, new, fragment) in cases.items():
            with self.subTest(label=label):
                self.assertIn(old, LOCK)
                errors = contract.check(self.tree(lock=LOCK.replace(old, new, 1)))
                self.assert_rejected(errors, fragment)

    def test_header_is_validated(self) -> None:
        cases = {
            "no python header": (
                "autogenerated by pip-compile with Python 3.12",
                "autogenerated",
                "with Python X.Y",
            ),
            "no-index bug": (
                "--generate-hashes --strip",
                "--generate-hashes --no-index --strip",
                "--no-index",
            ),
            "no hashes flag": ("--generate-hashes ", "", "does not --generate-hashes"),
        }
        for label, (old, new, fragment) in cases.items():
            with self.subTest(label=label):
                errors = contract.check(self.tree(lock=LOCK.replace(old, new, 1)))
                self.assert_rejected(errors, fragment)

    def test_lock_must_cover_its_source(self) -> None:
        self.assert_rejected(
            contract.check(self.tree(source=SOURCE + "twine\n")), "does not lock ['twine']"
        )
        self.assert_rejected(contract.check(self.tree(source=None)), "missing requirements source")
        self.assert_rejected(contract.check(self.tree(lock=None)), "lock file does not exist")

    def test_source_specifiers_must_hold_for_the_locked_versions(self) -> None:
        """Name coverage alone let `build<1.6` pass against a lock pinning 1.6.1."""
        self.assertEqual(
            contract.check(self.tree(source="build[virtualenv]>=1.6,<2\nsetuptools\n")), []
        )
        cases = {
            "build<1.6\nsetuptools\n": "violates release.in specifier '<1.6'",
            "build>=1.0rc1\nsetuptools\n": "cannot evaluate locked build==1.6.1",
        }
        for source, fragment in cases.items():
            with self.subTest(source=source):
                self.assert_rejected(contract.check(self.tree(source=source)), fragment)

    def test_source_lines_the_gate_cannot_vouch_for_are_refused(self) -> None:
        cases = {
            'tomli; python_version < "3.11"\n': "environment marker",
            "-c constraints.txt\n": "option line '-c'",
            "build @ https://example.invalid/build.whl\n": "direct reference",
        }
        for extra, fragment in cases.items():
            with self.subTest(extra=extra):
                self.assert_rejected(contract.check(self.tree(source=SOURCE + extra)), fragment)

    def test_locked_backend_must_satisfy_pyproject(self) -> None:
        errors = contract.check(self.tree(pyproject=PYPROJECT.replace(">=77.0", ">=85")))
        self.assert_rejected(errors, "violates pyproject.toml build-system requirement")
        errors = contract.check(
            self.tree(
                pyproject=PYPROJECT.replace('"setuptools>=77.0"', '"setuptools>=77.0", "wheel"')
            )
        )
        self.assert_rejected(errors, "'wheel' is not locked")

    def test_lock_python_must_match_the_workflow(self) -> None:
        errors = contract.check(self.tree(workflow=WORKFLOW.replace('"3.12"', '"3.13"')))
        self.assert_rejected(errors, "differs from the Python 3.12")
        errors = contract.check(
            self.tree(workflow=WORKFLOW.replace('          python-version: "3.12"\n', ""))
        )
        self.assert_rejected(errors, "pins no python-version")

    # --- workflow inventory ------------------------------------------------

    def test_unlisted_publishing_workflow_is_rejected(self) -> None:
        publisher = "jobs:\n  p:\n    steps:\n      - uses: pypa/gh-action-pypi-publish@0\n"
        errors = contract.check(self.tree(extra_workflows={"release2.yml": publisher}))
        self.assert_rejected(errors, "release2.yml: publishes to PyPI")
        for command in (
            "uv publish",
            "poetry publish --build",
            "hatch publish",
            "twine upload dist/*",
        ):
            with self.subTest(command=command):
                workflow = f"jobs:\n  p:\n    steps:\n      - run: {command}\n"
                errors = contract.check(self.tree(extra_workflows={"r.yml": workflow}))
                self.assert_rejected(errors, "r.yml: publishes to PyPI")
        commented = "jobs:\n  p:\n    steps:\n      # pypa/gh-action-pypi-publish\n"
        self.assertEqual(contract.check(self.tree(extra_workflows={"ci.yml": commented})), [])

    def test_missing_release_workflow_is_rejected(self) -> None:
        root = self.tree()
        (root / ".github" / "workflows" / "pypi.yml").unlink()
        self.assert_rejected(contract.check(root), "listed release workflow is missing")

    # --- YAML validity of inline values ------------------------------------

    def test_inline_colon_space_makes_the_workflow_unparsable(self) -> None:
        """The defect this PR's own first draft had (zizmor skipped it, exit 0)."""
        workflow = WORKFLOW.replace(f"run: |\n          {INSTALL}", f"run: {INSTALL}")
        self.assertNotEqual(workflow, WORKFLOW)
        self.assert_rejected(contract.check(self.tree(workflow=workflow)), "YAML mapping indicator")

    def test_plain_scalar_scanner_reads_only_inline_values(self) -> None:
        text = (
            "on:\n  release:\n    types: [published]\n"
            "env:\n  URL: https://pypi.org/p/liouscope\n  QUOTED: 'a: b'\n"
            "jobs:\n  j:\n    steps:\n      - run: |\n          echo a: b\n"
            "          key: value:\n      - name: after the block\n"
            "        if: ${{ github.event_name == 'release' }}  # note: fine\n"
        )
        self.assertEqual(contract.plain_scalar_defects(text), [])
        broken = text.replace("- name: after the block", "- name: after: the block")
        self.assertEqual(len(contract.plain_scalar_defects(broken)), 1)
        self.assertEqual(len(contract.plain_scalar_defects("  run: echo trailing:\n")), 1)

    # --- specifier evaluation ----------------------------------------------

    def test_specifier_evaluation(self) -> None:
        self.assertTrue(contract.satisfies("84.0.0", ">=77.0"))
        self.assertFalse(contract.satisfies("76.1", ">=77.0"))
        self.assertTrue(contract.satisfies("77.0.0", "==77"))
        self.assertTrue(contract.satisfies("77.3", "~=77.1"))
        self.assertFalse(contract.satisfies("78.0", "~=77.1"))
        self.assertFalse(contract.satisfies("80", ">=77,!=80"))
        self.assertIsNone(contract.satisfies("80.0rc1", ">=77"))
        self.assertIsNone(contract.satisfies("80.0", "===80.0"))
        self.assertIsNone(contract.satisfies("80.0", "~=80"))


if __name__ == "__main__":
    unittest.main()
