"""PR #170 review findings against the release gate, one discriminating test each.

Six Codex findings (2026-09-26) on ``check_release_pins.py``, ``compare_dists.py``
and ``pypi.yml``; four of them reproduced by Equalita as silent passes of the
release hash-pin gate. Each test below fails on 429ecf8 and passes on the fix;
each rejection sits next to a positive control that differs in one aspect only.

The gate reads workflows with a strict YAML subset reader of its own (the
quality contract installs nothing). Its decoding is pinned against values
PyYAML's ``BaseLoader`` produced, and re-derived live from PyYAML wherever it is
installed.
"""

from __future__ import annotations

import io
import sys
import tarfile
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / ".github" / "scripts"))

import check_release_pins as gate  # noqa: E402
import compare_dists  # noqa: E402

HASH = "a" * 64
LOCK_HEADER = (
    "#\n# This file is autogenerated by pip-compile with Python 3.12\n"
    "# by the following command:\n#\n"
    "#    pip-compile --allow-unsafe --generate-hashes --strip-extras release.in\n#\n"
)


def _workflow(run_block: str) -> str:
    return (
        "name: Publish\non: workflow_dispatch\npermissions: {}\njobs:\n  build:\n"
        "    runs-on: ubuntu-latest\n    steps:\n"
        "      - run: |\n"
        "          python -m pip install --require-hashes -r .github/requirements/release.txt\n"
        f"{run_block}"
    )


def _reasons(text: str) -> list[str]:
    installs, unreadable = gate.find_pip_installs(text)
    return [r for r in (gate.classify(i) for i in installs) if r] + unreadable


# --- check_release_pins.py:197 -- a folded block is ONE shell command --------


def test_folded_run_block_is_read_as_one_command() -> None:
    folded = _workflow("      - run: >-\n          python -m pip\n          install build\n")
    assert any("not hash-pinned" in r for r in _reasons(folded)), _reasons(folded)


def test_literal_run_block_keeps_two_commands() -> None:
    """Positive control: in a LITERAL block the same two lines are two commands."""
    literal = _workflow("      - run: |\n          python -m pip\n          install build\n")
    assert _reasons(literal) == []


def test_pip_and_install_without_a_recognised_invocation_fail_closed() -> None:
    wrapped = _workflow('      - run: bash -c "pip install build"\n')
    assert any("no recognised pip invocation" in r for r in _reasons(wrapped)), _reasons(wrapped)


@pytest.mark.parametrize(
    "command",
    ["$PIP install build", "pip $CMD build", "python -m $MODULE install build"],
)
def test_installs_through_a_shell_expansion_fail_closed(command: str) -> None:
    """Found by running the gate's own fault class against it: the command or
    pip's sub-command decided at run time was invisible (no literal
    ``pip``+``install`` pair on the line)."""
    text = _workflow(f"          {command}\n")
    assert any("expansion" in r for r in _reasons(text)), _reasons(text)


def test_pip_commands_that_do_not_install_stay_clean() -> None:
    """Positive control for the nets above."""
    text = _workflow("          python -m pip check && pip --version && echo $HOME\n")
    assert _reasons(text) == []


def test_workflow_outside_the_yaml_subset_fails_closed() -> None:
    anchored = _workflow("      - run: &cmd pip install build\n")
    installs, unreadable = gate.find_pip_installs(anchored)
    assert installs == []
    assert any("cannot read the workflow as YAML" in r for r in unreadable), unreadable


# --- check_release_pins.py:336 -- the local-wheel exception -------------------


@pytest.mark.parametrize(
    "path",
    [
        '"$BASE/pkg.whl"',
        "${BASE}/pkg.whl",
        '"$(echo https://h)/pkg.whl"',
        "/abs/dist/pkg.whl",
        "../dist/pkg.whl",
        "dist/../pkg.whl",
        "file:dist/pkg.whl",
    ],
)
def test_expanded_or_foreign_wheel_paths_are_rejected(path: str) -> None:
    text = _workflow(f"          python -m pip install --no-deps {path}\n")
    assert any("not hash-pinned" in r for r in _reasons(text)), _reasons(text)


@pytest.mark.parametrize("path", ["dist/*.whl", "dist/liouscope-0.6.0-py3-none-any.whl"])
def test_literal_wheels_in_the_build_directory_stay_allowed(path: str) -> None:
    text = _workflow(f"          python -m pip install --force-reinstall --no-deps {path}\n")
    assert _reasons(text) == []


# --- check_release_pins.py:373 -- lock markers are evaluated ------------------


def _lock(entry: str) -> str:
    return f"{LOCK_HEADER}{entry} \\\n    --hash=sha256:{HASH}\n    # via -r release.in\n"


def test_lock_entry_excluded_by_its_marker_is_not_a_pin() -> None:
    lock, errors = gate.parse_lock(_lock('setuptools==84.0.0 ; python_version < "3"'))
    assert "setuptools" not in lock.pins
    assert not any("setuptools" in e for e in errors), errors


def test_lock_entry_included_by_its_marker_is_a_pin() -> None:
    lock, errors = gate.parse_lock(_lock('setuptools==84.0.0 ; python_version >= "3.11"'))
    assert lock.pins == {"setuptools": "84.0.0"}
    assert errors == []


@pytest.mark.parametrize(
    "marker",
    [
        'sys_platform == "linux"',
        'python_version ~= "3.12"',
        'python_version >= "3.*"',
        'python_version in "3.12"',
        'python_version >= "3.11" and',
    ],
)
def test_lock_marker_the_gate_cannot_evaluate_fails_closed(marker: str) -> None:
    lock, errors = gate.parse_lock(_lock(f"setuptools==84.0.0 ; {marker}"))
    assert "setuptools" not in lock.pins
    assert any("cannot evaluate environment marker" in e for e in errors), errors


@pytest.mark.parametrize(
    ("marker", "expected"),
    [
        ('python_version < "3.11"', False),
        ('python_version >= "3.12"', True),
        ('"3.13" > python_version', True),
        ('python_version == "3.12.0"', True),
        ('python_version < "3.11" or python_version >= "3.12"', True),
        ('(python_version >= "3.8" and python_version < "3.12")', False),
    ],
)
def test_marker_evaluation(marker: str, expected: bool) -> None:
    assert gate.evaluate_marker(marker, "3.12") is expected


# --- check_release_pins.py:680 -- publishers are found on shell tokens --------


@pytest.mark.parametrize(
    "run",
    [
        "twine  upload dist/*",
        "|\n          twine \\\n            upload dist/*",
        "python -m twine upload dist/*",
        "uv  publish",
        # Only the token scan sees these; the whitespace-collapsed substring
        # net (kept as an addition) does not.
        "twine --verbose upload dist/*",
        "python -m 'twine' upload dist/*",
        "poetry -v publish",
    ],
)
def test_publish_commands_are_recognised_on_tokens(run: str) -> None:
    text = f"jobs:\n  x:\n    steps:\n      - run: {run}\n"
    evidence, unreadable = gate.publish_evidence(text)
    assert unreadable is None
    assert evidence, text


def test_non_publishing_twine_and_the_action_by_uses() -> None:
    quiet, _ = gate.publish_evidence("jobs:\n  x:\n    steps:\n      - run: twine check dist/*\n")
    assert quiet == []
    action, _ = gate.publish_evidence(
        "jobs:\n  x:\n    steps:\n      - uses: pypa/gh-action-pypi-publish@v1.14.0\n"
    )
    assert action


def test_unreadable_workflow_cannot_be_ruled_out_as_a_publisher() -> None:
    _, unreadable = gate.publish_evidence("jobs:\n  x:\n    steps:\n      - run: *alias\n")
    assert unreadable is not None


@pytest.mark.parametrize(
    "step",
    [
        "- run: $TOOL upload dist/*",
        "- uses: ./.github/actions/release",
        "- uses: other/repo/.github/workflows/publish.yml@0123456789abcdef",
    ],
)
def test_publishing_the_scan_cannot_inspect_is_not_cleared(step: str) -> None:
    _, unreadable = gate.publish_evidence(f"jobs:\n  x:\n    steps:\n      {step}\n")
    assert unreadable is not None, step


def test_inspectable_steps_are_cleared() -> None:
    """Positive control: a local reusable workflow and artifact upload are fine."""
    evidence, unreadable = gate.publish_evidence(
        "jobs:\n  x:\n    uses: ./.github/workflows/ci-python-local.yml\n"
        "  y:\n    steps:\n      - uses: actions/upload-artifact@v4\n"
        '      - run: echo "$GITHUB_SHA"\n'
    )
    assert (evidence, unreadable) == ([], None)


# --- compare_dists.py:73 -- PAX records are content ---------------------------


def _sdist(path: Path, pax: dict[str, str]) -> None:
    with tarfile.open(path, mode="w:gz", format=tarfile.PAX_FORMAT) as archive:
        data = b"print('hi')\n"
        info = tarfile.TarInfo("pkg-1.0/pkg.py")
        info.size = len(data)
        info.pax_headers = pax
        archive.addfile(info, io.BytesIO(data))


def _compare(tmp_path: Path, first: dict[str, str], second: dict[str, str]) -> list[str]:
    a, b = tmp_path / "a", tmp_path / "b"
    a.mkdir()
    b.mkdir()
    _sdist(a / "pkg-1.0.tar.gz", first)
    _sdist(b / "pkg-1.0.tar.gz", second)
    errors, _report = compare_dists.compare(a, b)
    return errors


def test_sdists_differing_in_a_pax_record_are_not_content_identical(tmp_path: Path) -> None:
    errors = _compare(
        tmp_path, {"SCHILY.xattr.user.origin": "build-a"}, {"SCHILY.xattr.user.origin": "build-b"}
    )
    assert any("sdist content differs" in e for e in errors), errors


def test_sdists_differing_only_in_volatile_pax_records_agree(tmp_path: Path) -> None:
    errors = _compare(
        tmp_path,
        {"mtime": "1.5", "uname": "runner", "uid": "1001"},
        {"mtime": "2.5", "uname": "builder", "uid": "0"},
    )
    assert errors == []


# --- pypi.yml:66 -- the second build starts from a clean tree ------------------


def test_second_release_build_runs_in_a_fresh_worktree() -> None:
    workflow = gate.load_workflow_yaml(
        (REPO / ".github" / "workflows" / "pypi.yml").read_text(encoding="utf-8")
    )
    steps = workflow["jobs"]["build"]["steps"]
    title = "Build sdist + wheel twice and verify reproducibility"
    (step,) = [s for s in steps if "name" in s and s["name"].value == title]
    lines = [line.strip() for line in step["run"].value.splitlines()]
    assert 'git worktree add --detach "$RUNNER_TEMP/rebuild-src" HEAD' in lines
    assert (
        '(cd "$RUNNER_TEMP/rebuild-src" && python -m build --no-isolation '
        '--outdir "$RUNNER_TEMP/rebuild")'
    ) in lines
    assert lines.index("python -m build --no-isolation --outdir dist") < lines.index(
        'git worktree add --detach "$RUNNER_TEMP/rebuild-src" HEAD'
    )
    assert not any(line.startswith("rm -rf") for line in lines)


# --- the strict YAML subset reader --------------------------------------------

#: Decoded values produced by PyYAML 6.0.3 ``yaml.load(text, Loader=BaseLoader)``
#: (re-derived live below where PyYAML is installed).
GOLDEN: dict[str, object] = {
    "on: [push, 'pull_request']\npermissions: {}\n": {
        "on": ["push", "pull_request"],
        "permissions": {},
    },
    "a: >-\n  python -m pip\n  install build\n\n  x\n    more\n  y\n": {
        "a": "python -m pip install build\nx\n  more\ny"
    },
    "a: |\n  one\n\n  two\nb: 'it''s'\nc: \"t\\tu\\u00e9\"\n": {
        "a": "one\n\ntwo\n",
        "b": "it's",
        "c": "t\tu\u00e9",
    },
    "s:\n- x\n- k: v\n  m: [1, \"2\"]\n": {"s": ["x", {"k": "v", "m": ["1", "2"]}]},
    "a: >\n  last\n": {"a": "last\n"},
    "a: |\n  no final break": {"a": "no final break"},
    "k: v  # comment\nl: ${{ x == 'a' }}\n": {"k": "v", "l": "${{ x == 'a' }}"},
}


@pytest.mark.parametrize("text", list(GOLDEN))
def test_reader_matches_pyyaml_golden(text: str) -> None:
    assert gate.yaml_plain(gate.load_workflow_yaml(text)) == GOLDEN[text]


@pytest.mark.parametrize(
    "text",
    [
        "a: &x 1\nb: *x\n",
        "a: !!str 1\n",
        "a: one\n  two\n",
        "a: 'one\n  two'\n",
        "a: 1\na: 2\n",
        "a:\n\t- x\n",
        "a: x\tb\n",
        "a: |2\n  x\n",
        "a: |+\n  x\n",
        "---\na: 1\n",
        "%YAML 1.1\n---\na: 1\n",
        "a: [x,\n  y]\n",
        "a: [:\"main\"]\n",
        "a: b: c\n",
        "? a\n: b\n",
        "<<: {a: 1}\n",
        "a: |\n    x\n   y\n  z\n",
    ],
)
def test_reader_refuses_constructs_outside_the_subset(text: str) -> None:
    with pytest.raises(gate.WorkflowYamlError):
        gate.load_workflow_yaml(text)


def test_reader_matches_pyyaml_live() -> None:
    yaml = pytest.importorskip("yaml")
    texts = list(GOLDEN) + [
        path.read_text(encoding="utf-8")
        for path in sorted((REPO / ".github" / "workflows").glob("*.yml"))
    ]
    for text in texts:
        assert gate.yaml_plain(gate.load_workflow_yaml(text)) == yaml.load(
            text, Loader=yaml.BaseLoader
        ), text[:80]
